### ISSUE TITLE
Browser tests - Need libraries installed on benchmark server

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#113]
Browser tests - we get the error `/home/ubuntu/ipfs/tests/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

I haven't tested this on the server but according to doc we need this ran on the benchmark server
`sudo apt-get install libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0`

**Comment by Elexy** [comment]
https://github.com/ipfs/benchmarks/pull/115
