### ISSUE TITLE
Do a video recording of the Runner/Architecture and Dashboard

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#140]
As titled and discussed in #44.

**Comment by Elexy** [comment]
https://cloudflare-ipfs.com/ipfs/QmSZgcL7dyjcifZ5uJYmBDCCACfzQD5Ve2RFSoB4RdYATp

**Comment by mcollina** [comment]
Can you add that in the README?

Il giorno lun 7 gen 2019 alle 22:02 Alex Knol <notifications@github.com> ha
scritto:
