### ISSUE TITLE
Include the full log of the run in the ipfs bundle

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#147]
As titled.

**Comment by Elexy** [comment]
PR here https://github.com/ipfs/benchmarks/pull/218

**Comment by Elexy** [comment]
https://cloudflare-ipfs.com/ipfs/QmTndWwrHRmvUhVdcej726VJgoWHLjvQCjEczx8kxGUyM7
is an example of a local run with clinic turned off
