### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Elexy** [ipfs/benchmarks#150]
@alanshaw The logs from the runner are currently only viewable on the VM.
Do you have a centralized logging server I can send the logs to for easy viewing and alerting?

Alternatively I could connect logz.io community edition or similar.

/cc @daviddias @mcollina

**Comment by Elexy** [comment]
@eefahy ^^

**Comment by eefahy** [comment]
We are standing one up presently for gateway monitoring. Should be in place by the end of this week

**Comment by Elexy** [comment]
Yes, it will. I can add a logstash transport to the ansible scripts.
How would you like to go about configuring endpoint, an IP I guess and installing the TLS cert?

I could prepare the ansible script with instructions on how to add the cert and configure the endpoint and then your team could run it? 
What do you think @eefahy ?

**Comment by eefahy** [comment]
Looking at the config for the VM, we don't have ssh access to the machine so I don't think we'd be able to run your ansible script. It would be easier for us to just provide you the url (`logstash.locotorp.info:5045`) and find a way to send you the cert. Do you happen to have a keybase account for that?

cc: @mburns

**Comment by Elexy** [comment]
Yes, I have a keybase account: `elexy`

**Comment by mburns** [comment]
sent!

**Comment by Elexy** [comment]
@mburns @eefahy I have a setup running, can you tell me if logs are reaching that server?

**Comment by Elexy** [comment]
Woohoo, we have runner logs: https://cloudflare-ipfs.com/ipfs/Qmc7fEUcBQEMMW7sJyHBS1ihyXmmBRhvEpTwpsnQYxrgfd
