### ISSUE TITLE
Date in dashboard does not match test date 

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#173]
<img width="1084" alt="screen shot 2019-01-10 at 7 04 01 am" src="https://user-images.githubusercontent.com/6003995/50970250-7c0f1280-14a6-11e9-8779-370d3c0adb74.png">
<img width="469" alt="screen shot 2019-01-10 at 7 04 19 am" src="https://user-images.githubusercontent.com/6003995/50970251-816c5d00-14a6-11e9-8c8a-11a6a2fdba07.png">

**Comment by Elexy** [comment]
Seems like a presentation problem in grafana
