### ISSUE TITLE
Add info in the README about repo layout, purpose, infra image, URLs for deployed services etc. 

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#18]
As discussed in #16.

**Comment by Elexy** [comment]
I will get a few things done for this issue:
* [ ] README to be updated with repo layout
* [ ] Add description of purpose
* [ ] Description of infra image
* [ ] URLs for deployed services etc
Will add links to PRs for each task

**Comment by Elexy** [comment]
Repo layout https://github.com/ipfs/benchmarks/pull/19

**Comment by Elexy** [comment]
@mcollina URL can be added when the system is deployed.

**Comment by alanshaw** [comment]
@Elexy FYI https://github.com/ipfs/benchmarks/blob/master/REPOSITORY.md linked to from the README is a 404 atm

**Comment by Elexy** [comment]
fixed in https://github.com/ipfs/benchmarks/pull/159, now pointing to https://github.com/ipfs/benchmarks/blob/master/CONTRIBUTING.md
