### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by Elexy** [ipfs/benchmarks#204]
Currently A full run including Clinic takes ~45 minutes.
@alanshaw @daviddias @hugomrdias when we start running these things on PRs or Commits and add even more tests or combinations, we quickly run out of hours in a day.

Maybe CI runs shouldn't include `clinic` by default, only if we see a performance issue (strong deviation) perhaps?

**Comment by vasco-santos** [comment]
I think we should run them automatically in each release for tracking history. Then, in the major features, we could simply have a way to trigger it manually

**Comment by hugomrdias** [comment]
i can add it as a manual job in the pipelines also could make sense to be able to select what gets ran with querystring params

**Comment by Elexy** [comment]
Thanks @hugomrdias.
Right now we can specify on the runners' API to included clinic or not. But we could pull more parts of the run config into the API. 
https://github.com/ipfs/benchmarks/blob/master/runner/config.js#L76
So the contents of `config.js` serves as a default and you can override through the API.

**Comment by alanshaw** [comment]
> Right now we can specify on the runners' API to included clinic or not. But we could pull more parts of the run config into the API.

+1

**Comment by Elexy** [comment]
@mcollina pulling the config out to the API is probably out of reach for this week i.e. done before Friday February 1st.

**Comment by Elexy** [comment]
@hugomrdias we can now limit the run to an array of named tests and whether to run clinic tools or not: https://github.com/ipfs/benchmarks/pull/236
