### ISSUE TITLE
Store benchmarks results in IPFS

### ISSUE THREAD

**Issue by Elexy** [ipfs/benchmarks#21]
@alanshaw Can you offer any guidance on how we can store the results of the benchmarks on IPFS?
Any specific location or format?

**Comment by litzenberger** [comment]
@alanshaw Could you provide us with an example of what is needed to send the files to the IPFS cluster?  Thanks

**Comment by alanshaw** [comment]
Update: I've been in touch with the cluster team and we're waiting on credentials to be approved. We'll need `ipfs-cluster-ctl` installed on the machine https://dist.ipfs.io/#ipfs-cluster-ctl

**Comment by hsanjuan** [comment]
It should be ready, let me know how to pass the credentials.

`ipfs-cluster-ctl --host /dnsaddr/cluster.ipfs.io --basic-auth <user:pw> add yourfile.bin` is the fastest way to add something to cluster.

**Comment by Elexy** [comment]
@hsanjuan I'm on keybase, does that help? 
https://keybase.io/elexy

**Comment by hsanjuan** [comment]
@Elexy 

```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.80
Comment: https://keybase.io/crypto

wcFMA8XqJM1TF7DGAQ//ZJSIwjaMnDe0mW9iDE7JG0Ml6HTRpVHuR3c8dt+DhWM4
zFCTvEuDSEv6ZtV7S3WoSWUMW2sJYkGVZ7bQwRuMmVxbTf61VOQHbxB0Fs9Wksbm
foxbjQH3O2SFGAgWgxP2Y2p2QegAIUaCrdXlFGijhkxiZba3xfftXSIQyvPzJgDr
MeTch+iXJr6iBmegmzrK1lI5ftHjf/MQs5Y2jZVCxVPM6UHUBuNo0AbEJDJ2UpD5
jBuCZ0tRy4ktqd039u+YVtmeUm34rXn3Nm31kS/5y4lAWqS28uo871qH5lpCTSzq
OXVG0fLK0hDANrmW0KYZRuvt5ZU+aW/dpCboXJqnicjjlYyGvDt2JR2GWmmy0lPI
XoNx3UiV79Pp7B0WRnH3vFCUnnew149r4Aq6ZsY3ruZjvNj3i5sLcPKpAm1jQfyo
5goUuVB2HYlMBGfnkW79gcXL5aT+Xl8m0KGDjIIXmpR1VMMMP7wqAmJ9xraliNCU
FraYhdHM/HryyDRCTzKqBGkoVRKkiX0B8B+MHFqjksVLKycue5k/cB8yldkIwZc3
vIjq3BR8uqyKrBH9L2EDuunvcW+LoFOWere+R4KZX+vt5nhJZyt5NrXaTwMSAz6r
04s5Eu2MJLhudzV6X6Wy3hkTmR2ZlE8s2sjmMiC53mdrqi0KOvRB4UMNJa1YJfDS
kAGfUMSdLoz26DoiJlmxUXZJgYmwIvMPP+HaLqV5lkzoQkxvuR6fkvKD8tE29LQA
87FJzMZRyW/mD89dtFx2Kt7VGE+no0i2ZJMMBiXKn4OE6nPNzw54uqievg/zqwQx
s0Ce38BG/Xsbfp2lPoIEDAaPKVgEn5JDpEHvACCiFwhZsGwYyFONL9y7pqDVG8vi
tg==
=R9ub
-----END PGP MESSAGE-----
```

**Comment by Elexy** [comment]
@alanshaw @hsanjuan trying to add a first clinic benchmark gives me this:
```
ipfs-cluster-ctl --host /dnsaddr/cluster.ipfs.io --basic-auth <user>:<pass> add -r /tmp/out/localAdd
An error occurred:
  Code: 500
  Message: not enough peers to allocate CID. Needed at least: 2. Wanted at most: 3. Valid candidates: 1. See logs for more info.
```

**Comment by alanshaw** [comment]
Sorry, js ipfs doesn’t talk to cluster and I dont think there’s a JS API client for it.

There is probably a way to put the content in JS IPFS and inform cluster to slurp it up but I dont know that process or if it’ll be any easier.

@hsanjuan would know more...

**Comment by hsanjuan** [comment]
hey @Elexy , I'm really sorry, the storage cluster suffered a problem just today and I was at a conference and travelling so it took some time to come into my attention. It should be fixed now.

**Comment by Elexy** [comment]
It works now, thanks. https://cloudflare-ipfs.com/ipfs/QmaEVMEEDjDnJAor6ayMQxSwgYJqsYCVHJcQZaHVFQgmTd

@hsanjuan Is there a `staging` IPFS I could use until I worked out the kinks?

**Comment by hsanjuan** [comment]
@Elexy not really, but @lanzafame can maybe provide it without much trouble? Anyways, if you're just pinning things it does not matter much if you leave some trash around.

**Comment by Elexy** [comment]
This is done: https://github.com/ipfs/benchmarks/pull/114
