### ISSUE TITLE
No such file or directory: './infrastructure/local/docker-compose.yaml'

### ISSUE THREAD

**Issue by alanshaw** [ipfs/benchmarks#22]
I'm running:

```sh
docker-compose -f infrastructure/local/docker-compose.yaml up
```

From https://github.com/ipfs/benchmarks/blob/master/runner/README.md

**Comment by Elexy** [comment]
@alanshaw that will be fixed and documented in this branch https://github.com/ipfs/benchmarks/tree/add-trigger

**Comment by Elexy** [comment]
merged https://github.com/ipfs/benchmarks/pull/23
