### ISSUE TITLE
Update test descriptions

### ISSUE THREAD

**Issue by alanshaw** [ipfs/benchmarks#220]
Currently descriptions in test files differ considerably from the description in the test matrix. Can these
be updated?

e.g.

test: https://github.com/ipfs/benchmarks/blob/master/tests/extract-go2.js#L42
Matrix: https://github.com/ipfs/benchmarks/tree/master/tests#nodejs-and-go

**Comment by litzenberger** [comment]
@alanshaw yes, will go through the test and update the descriptions based on the matrix.

**Comment by litzenberger** [comment]
Updated test description based on test matrix
