### ISSUE TITLE
API add nightly param

### ISSUE THREAD

**Issue by Elexy** [ipfs/benchmarks#244]
like title
/cc @hugomrdias

**Comment by Elexy** [comment]
@hugomrdias for CI you need to specify the `x-ipfs-benchmarks-api-key` 
Do you have a keybase account I could use to send the api key to?

**Comment by hugomrdias** [comment]
yeah just sent you a follow

**Comment by Elexy** [comment]
[This ](https://github.com/ipfs/benchmarks/pull/251) PR adds the nightly parm to the API
