### ISSUE TITLE
benchmark.ipfs.team is down

### ISSUE THREAD

**Issue by daviddias** [ipfs/benchmarks#262]
@mburns can you check this?

**Comment by jimpick** [comment]
Seems to have been fixed.

**Comment by daviddias** [comment]
@mburns wanna give a quick write up here of what it was or point to the issues that walk us through the fix?

**Comment by alanshaw** [comment]
The machine was restarted and no systemd config exists to bring the docker service back up. I've created an issue here so we can address the issue https://github.com/ipfs/benchmarks/issues/272
