### ISSUE TITLE
sizes of files to add 

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#28]
We are currently uploading a 1 MB and 10KB files. What are representatives numbers for ipfs? Should we benchmark with 10 MB, 100 MB and maybe even 1 GB?

@alanshaw can you help with some guidance here?

**Comment by mcollina** [comment]
I've generated a flamegraph:

https://upload.clinicjs.org/public/e68fab713e740f151ae0e64c2de8b2cd2dbf75cb38300f177ba836c008a58980/66859.clinic-flame.html

and as you can see there are no clear bottlenecks, and most of those are initialization things. We just don't have enough data.

I've also generated a bubbleprof diagram: https://upload.clinicjs.org/public/1dd8f6f876c572334c0000e377e102db1286027d50d443e25e5cf87d4ef0c59c/66962.clinic-bubbleprof.html

This is also in agreement that these files are too small to generate reliable data.

**Comment by mcollina** [comment]
The sizes should be in https://github.com/ipfs/interop/blob/master/test/exchange-files.js.

@litzenberger can you use these?

**Comment by litzenberger** [comment]
These have been added and a pre-generated script.
