### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by litzenberger** [ipfs/benchmarks#50]
- [x] Node initialization - Node.js (timing around creating a repo without pregen key)
- [x] Node initialization - Browser
- [x] Add files - Browser
- [x] Cat files (websocket, mplex, secio) js0 -> js1 - Browser
- [x] Cat files (websocket, mplex) - Node.js
- [x] Cat files (websocket, mplex, secio) js01234->js5 - Node.js

**Comment by mcollina** [comment]
Is "Add files" done in #153? Can you please update the big table in the README?

**Comment by litzenberger** [comment]
Yes, add single file and the 100 small files are done on the dashboard.  README big table is current.
https://github.com/ipfs/benchmarks/tree/master/tests
