### ISSUE TITLE
Add a page in our benchmarks about all the runs with the links to ifs

### ISSUE THREAD

**Issue by mcollina** [ipfs/benchmarks#73]
Basically we should:

* [x] upload all the result and clinic data into a folder, adding it to ipfs will return an hash
* [x] store the hash for each run that we do in influxdb or a JSON file
* [x] add an html page in our runner that gets that data, and display them in a list. It would be fantastic to also include a number from one of the benchmarks, and maybe a quick summary of all the data for each run.
* [x] add pagination to that list

---

@litzenberger can you do the necessary work in the runner to add this feature?

@Elexy can you sort out the uploading to ipfs?

**Comment by litzenberger** [comment]
This is now in Grafana

<img width="1845" alt="screen shot 2019-01-02 at 2 38 57 am" src="https://user-images.githubusercontent.com/6003995/50584860-a1ad7380-0e37-11e9-8e3f-b15329945952.png">

**Comment by mcollina** [comment]
I cannot access: https://github.com/ipfs/benchmarks/issues/135.
